apiVersion: v1
kind: Pod
metadata:
  labels:
    mutation-check: enabled
  name: lifespan-seven
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: lifespan-seven
  restartPolicy: Always
