apiVersion: v1
kind: Pod
metadata:
  labels:
    mutation-check: enabled
    validation-check: enabled
  name: test-pod
  namespace: apps
spec:
  containers:
    - args:
        - sleep
        - "3600"
      image: busybox
      name: lifespan-seven
    - image: nginx:latest
      name: nginx
      resources:
        requests:
          cpu: 100m
          memory: 32M
        limits:
          cpu: 200m
          memory: 64M
  restartPolicy: Always
