apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "kubernetes-webhook.acme.com"
webhooks:
  - name: "kubernetes-webhook.acme.com"
    objectSelector:
      matchLabels:
        mutation-check: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "*"
    clientConfig:
      service:
        namespace: default
        name: kubernetes-webhook
        path: /mutate-pods
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwRENDQWJnQ0NRQ3c5aXE3aUZaWU56QU5CZ2tx
        aGtpRzl3MEJBUXNGQURBcU1Rc3dDUVlEVlFRR0V3SkIKVlRFYk1Ca0dBMVVFQXd3U2EzVmlaWEp1WlhS
        bGN5MTNaV0pvYjI5ck1CNFhEVEl5TURReE1ERXdNRFl5T1ZvWApEVEl6TURReE1ERXdNRFl5T1Zvd0tq
        RUxNQWtHQTFVRUJoTUNRVlV4R3pBWkJnTlZCQU1NRW10MVltVnlibVYwClpYTXRkMlZpYUc5dmF6Q0NB
        U0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUx6RGdmMUEKalJyN1hiamMwKzhJ
        OXVZTHI1Z1NOaytjZms3TGs3ZGRRZmpWSGoyVmxRTi84d2gxcHhLWFZtL0dEYmRsWnNUQQowcXl2czhl
        VDhKRG1oZ1Y3VFZZaEhRR2FQR1RlaDhobFZndkJLdDhHakJ3QnBpVHhNNVNPRllML1lGajlHY1hECjRR
        RlNldDgwUDc0bWdtenloMlJoUkh2ZWZZMkJMMFdaUkhsRHZvZSt3TVdaRDVQZDhGcFJ1ZEorS21FL1hZ
        OFYKc1oxSExOclJxcWh3VzR1endQTzdKa3M5ZmtRWUZUblN4ZVJuQVVXVlFxSjl6MXZQQWMvOUxDZHhu
        YW94Qy95Vwpva0pHTzdScFN3RGhTTWUvL0dtSTlmeG4rRUx4cExYdkY4dWJrUmRNVGQ1QWJYY1RranAr
        UGtTTU94cXBLcXlkCklnZFNEZmZwRmNqN2o0MENBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFF
        QWxZcEVDdVJNemx6VmFqeUMKTlFGbHJCeG55bXlRRW94Q3NqcFc1OFZuNVZVQ3gwdXYvT1U0dmFUNndW
        TXVNYXluS3l5RXpNWjZDTmZZMGRiUAp6VmRwTHRGV3dyTnh0QXZLaldZdVFYU0VyZWlOdXJ0S3NMWWpl
        Y3oxTWNKWFV1YS9MS3VvOHl1UmhkMlZCb1U3Cmo1aVR5M2FSb3VoaUliRVI0cDdZWTh4RWh0SkZHeEhW
        K1l6K0hpdzZ2czNyd2c2aUdmQW5qWkpQSkdMVzFvZWUKRVJlaXpFTWpnZW5CazViQlhFaU5STTd6anY5
        dlZwcFVBbHkvRGFyQWVDVVp4ZHlNTTNmcjFwTFhseEhMV0dTWgo0SlhnbHB0M3U2azN1ZjVLc29kUUxQ
        clUveE16N0FwTWhQYms4S3RNRmlxVnpSaldudFlSaW1sTHZ0cGJKeGpyCmg4eDJFQT09Ci0tLS0tRU5E
        IENFUlRJRklDQVRFLS0tLS0K
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
